services:
  server-monitor:
    build: .
    container_name: server-monitor
    restart: unless-stopped
    env_file:
      - .env
    network_mode: host
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
